### ISSUE TITLE
Is A License File Needed?

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/coder_upgrade#10]
A reference is mentioned in the readme, but there is no license file included in this repo. I'm not sure which license to include though. The readme lists GPL 2.

In a lot of the Backdrop contrib module repos, there is no license file; however, it is packaged in the releases, I think. So, this issue affects all the contrib modules.

I was looking for an issue about this topic, but I couldn't find one via a basic search. I know @kreynen knows a lot about licensing and where to put them and may have created issues about this already.

I included a license in https://github.com/backdrop-contrib/xmlsitemap and https://github.com/backdrop-ops/contrib/blob/master/README.md#new-project-checklist has including a license as a requirement.

**Comment by docwilmot** [comment]
Thanks. Fixed in latest release.
