### ISSUE TITLE
Error when updating/installing the module

### ISSUE THREAD

**Issue by korontari** [backdrop-contrib/coder_upgrade#11]
There is an error when trying to update the module from Backdrop UI:
![2019-01-29_14-12-45](https://user-images.githubusercontent.com/44873997/52011293-99089580-24e8-11e9-8175-f9a33b19d4c6.png)
![2019-01-29_14-46-52](https://user-images.githubusercontent.com/44873997/52011294-99a12c00-24e8-11e9-9af9-8b51b1ae7b0d.png)

**Comment by docwilmot** [comment]
There is a core issue with downloading modules through the Installer. Just download the zip from GitHub.

**Comment by laryn** [comment]
@korontari Or add this patch until the next bug release:
https://github.com/backdrop/backdrop-issues/issues/3488

**Comment by korontari** [comment]
@docwilmot @laryn Oh, I got it. Looks like Coder Upgrade was the only module I tried updating. Thank you for the patch, @laryn!
