### ISSUE TITLE
The warning message on convert files

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/coder_upgrade#19]
Converting files is giving the warning:

```
WARNING: "CONTINUE" TARGETING SWITCH IS EQUIVALENT TO "BREAK". DID YOU MEAN TO USE "CONTINUE 2"? IN /VAR/WWW/DOCROOT/MODULES/CODER_UPGRADE/GRAMMAR_PARSER/EDITOR.INC ON LINE 309
```

and the long CALL STACK. Is ti normal behavior or a bug?

**Comment by docwilmot** [comment]
@alanmels Coder occasionally will throw strange errors; did it convert the code though?

**Comment by alanmels** [comment]
Well, it did, but the whole thing is not working yet, so I believe some manual work is needed. 

Also, I tried to use coder_upgrade with another module and this time it went through without the warning notice, so I believe the first time it was not about the coder_upgrade, but the module being upgraded. And therefore I mark this as closed.

**Comment by oadaeh** [comment]
That notice is related to PHP 7.3: https://wiki.php.net/rfc/continue_on_switch_deprecation
It should be found and fixed.

**Comment by alanmels** [comment]
> That notice is related to PHP 7.3: https://wiki.php.net/rfc/continue_on_switch_deprecation
> It should be found and fixed.

Unfortunately, I don't have a time to backtrace to the source of issue, but if someone wants to take a stab, then the module I attempted to convert was https://www.drupal.org/project/stickynote.

**Comment by alanmels** [comment]
Please review the PR. Tests on a system with PHP 7.1.23 (where the issue was taking place before the fix) show the warning messages are gone and modules covert normally as before.

**Comment by docwilmot** [comment]
Thanks @alanmels
