### ISSUE TITLE
Config "Run" page: Select all rows checkbox selects options in all vertical tabs

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/coder_upgrade#27]
There are four vertical tabs on `admin/config/development/coder-upgrade`
- Upgrades
- Extensions
- Directories
- Modules

Each of the tabs displays a list of options.

When I select the "Select all rows" option at the top of **one tab**, the rows of **all tabs** get selected. This can e.g. lead to a situation where *Coder upgrade* tries to convert all modules of a site.

**Steps to Reproduce (Example)**

- Install *Coder Upgrade*.
- Go to `admin/config/development/coder-upgrade`.
- Select the vertical tab *Extensions*, and check the "Select all rows" option at the top.
- NOTE: **Do not** hit the **Convert files** button.
- Have a look at one of the other vertical tabs, e.g. *Modules*.

Result:

- All options of the *Modules* tab (and of the other tabs) are enabled.
(If you'd hit **Convert files**; *Coder upgrade* would try to convert all modules of the site.)

Expected behavior:

- Only the rows of the initial / current tab are selected.

**Comment by alanmels** [comment]
I do confirm that if you select all rows in any of the tabs, then all rows of all tabs are selected.

**Comment by docwilmot** [comment]
It may seem this is a problem with tableselect in Backdrop, not Coder's fault. Issue posted at https://github.com/backdrop/backdrop-issues/issues/4231

**Comment by bugfolder** [comment]
The issue was fixed a while back in Backdrop core (in the issue above), and I confirm that it no longer afflicts Coder Upgrade module, so closing the issue.
