### ISSUE TITLE
ParseError: syntax error, unexpected 'NULL' (T_STRING)

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/coder_upgrade#30]
In some cases, the module gives:

`
ParseError: syntax error, unexpected 'NULL' (T_STRING), expecting ']' in coder_upgrade_cache_info_hooks() (line 5 of /var/www/docroot/modules/coder_upgrade/conversions/begin.inc(139) : eval()'d code).`

**Comment by bugfolder** [comment]
@alanmels, can you provide a sample module that causes this failure? Ideally, trimming the source module down to just the part that elicits the failure.

**Comment by alanmels** [comment]
@bugfolder, unfortunately I don't remember which exact module we tried to port back in December 2020 as we have done so many. We can close this one until someone else report it again providing more context.
