### ISSUE TITLE
Parser incorrectly replacing detrimental line of code.

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/coder_upgrade#31]
Upgraded an internal module to work with BackDrop CMS and afterwards noticed this in the generated path file.

```public static function create($object) {
-    $class = static::class;
+    $class =::;
```

It replaced `static::class;` entirely with T_DOUBLE_COLON, or `::`

I believe this is an issue but I'm not sure where this should be reported.

Thank you and cheers.

**Comment by docwilmot** [comment]
Should be fixed by https://github.com/backdrop-contrib/coder_upgrade/commit/25a1e4a4cec6b581692d3d11fcba8dfe3760db9a

**Comment by rbargerhuff** [comment]
Thank you!
