### ISSUE TITLE
Doesn't support ?? operator

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/coder_upgrade#33]
The null coalescing operator ?? gets dropped.

`$foo = $bar ?? $baz;` becomes
`$foo = $bar $baz;`

This was [introduced in PHP 7](https://www.php.net/manual/en/migration70.new-features.php), so shouldn't be used in contrib modules that are supporting back to PHP 5.3, but users might be converting custom modules that are only intended to run on PHP 7 and above.

**Comment by bugfolder** [comment]
Fixed by PR https://github.com/backdrop-contrib/coder_upgrade/pull/38.

**Comment by docwilmot** [comment]
Merged.
