### ISSUE TITLE
Travis tests fail php 5.3 for PRs for reasons unrelated to the PR

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/coder_upgrade#34]
[Moved from this issue](https://github.com/backdrop-contrib/coder_upgrade/issues/28#issuecomment-783149323) per @indigoxela. 

See php 5.3 failure on [this PR](https://travis-ci.com/github/backdrop-contrib/coder_upgrade/jobs/484900072).

**Comment by docwilmot** [comment]
Travis isnt set up on this repository, so we don't need it. Deleted.
