### ISSUE TITLE
Regarding PHP 7.1.x Nullable Types - Space being added between ? & type

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/coder_upgrade#39]
Upgraded an internal module to work with Backdrop CMS and afterwards noticed that a space has been added between the question mark and the type. I'm not sure if this is intended behavior or not.

Example:

```public static function logEntry(? string $logMessage) {```

Preferred:

```public static function logEntry(?string $logMessage) {```

Again, not sure if this is a bug.

Thank you and cheers.

**Comment by docwilmot** [comment]
Shouold be fixed in latest.

**Comment by rbargerhuff** [comment]
Thank you!

**Comment by rbargerhuff** [comment]
@docwilmot After pulling the latest of 1.x-1.x, we found that there were still issues with the nullable operator and its handling.

```
function online_admin_form_rules_ui_add_edit_element_callback(? array &$form, ? array &$formState, ?string $formId) {
```

We made the following change and this seems to have fixed the above issue we were seeing in many places.

```
diff --git a/grammar_parser/reader.inc b/grammar_parser/reader.inc
index 627b06c..cae8e96 100644
--- a/grammar_parser/reader.inc
+++ b/grammar_parser/reader.inc
@@ -1776,7 +1776,7 @@ class PGPReader extends PGPParser {
           break;
 */
         case '?':
-          if ($this->nextRealToken() == T_STRING) {
+          if ($this->nextRealToken() == T_STRING || $this->nextRealToken() == T_ARRAY) {
             // Nullable types.
             $node->setData('operator2', $this->tokenValue());
           }
 ```

Please let us know what you think.

**Comment by docwilmot** [comment]
This seems reasonable. I believe it illustrates though, that this module can only do some of the work. It is probably near impossible to predict all the possible permutations of different strings that make up code.

**Comment by bugfolder** [comment]
Fixed by https://github.com/backdrop-contrib/coder_upgrade/pull/41.
