### ISSUE TITLE
Issue: Handling of namespaces, ie: use statements and paths. Patch available.

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/coder_upgrade#40]
@docwilmot Hello there, during our testing and extensive evaluation of Coder Upgrade module, we discovered that namespaces, such as the following were not being handled at all.

```
namespace taco; /* Standard namespace statement */
namespace taco\cat; // Sub-namespace

use Drush\Backdrop; /* Standard use statement */
use Drush\Boot as TestAlias; // Use statement with alias
```

We took it upon ourselves to address this after forking this project and we will be pushing our changes soon.

**Comment by bugfolder** [comment]
Fixed by https://github.com/backdrop-contrib/coder_upgrade/pull/41.
