### ISSUE TITLE
Internal/helper functions being ignored.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/coder_upgrade#61]
Checking the log after conversion, I see entries like the following:

```
Ignoring function '_some_module_some_function' as its name does not begin with the module name or 'theme_'
```

We need to tweak the regex so not to be skipping `_module_name_*()` functions. Those should be converted too.

**Comment by klonos** [comment]
PR up for review @bugfolder and/or @docwilmot:https://github.com/backdrop-contrib/coder_upgrade/pull/62

...this is the first time I'm contributing to this module, so not 100% sure if there are other things that I've missed.

**Comment by bugfolder** [comment]
Tested the PR; works for me.
