### ISSUE TITLE
.info file fails to be converted if there are no spaces in the "core=" line

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/coder_upgrade#64]
- `core = 7.x` works 👍🏼 
- `core= 7.x` fails 👎🏼 
- `core =7.x` fails 👎🏼 
- `core=7.x` fails 👎🏼 

PS: perhaps this works as expected if the "Coding standards for Backdrop..." option is selected, but we can do better.

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop-contrib/coder_upgrade/pull/65

**Comment by bugfolder** [comment]
Tested. Works for me.
