### ISSUE TITLE
Warning on upgrade of (sub)modules with no hook_update

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/coder_upgrade#7]
`ERROR: max(): Array must contain at least one element on line 424 in [...]/modules/coder_upgrade/conversions/end.inc (Warning) `

**Comment by laryn** [comment]
Not 100% sure it's okay to just skip creating the `_update_last_removed` but if there isn't one to remove I guess there isn't something to add?

**Comment by docwilmot** [comment]
Thanks. Fixed in latest release.
