### ISSUE TITLE
Error when converting a module (using PHP 8.1)

### ISSUE THREAD

**Issue by rayjamesdev** [backdrop-contrib/coder_upgrade#81]
Info:
Fresh install of : Backdrop 1.24.0
Coder_Upgrade version: 1.x-1.0.8
Windows 11
Xampp version 8.1.12
PHP Version: 8.1.12
MySQL Version: 8.0.32 - MySQL Community Server - GPL

WATCHDOG ERROR:
TypeError: set_exception_handler(): Argument #1 ($callback) must be a valid callback or null, class PGPReader does not have a method "exception_handler" in set_exception_handler() (line 107 of D:\xampp8.1.12\htdocs\mysite\site\modules\Contrib\coder_upgrade\grammar_parser\parser.inc).

![convert_error](https://user-images.githubusercontent.com/51662089/217961130-d27181a8-aa8b-47ae-9920-a927096c21e9.jpg)

**Comment by klonos** [comment]
@rayjamesdev have you tried the `php-8.1` branch? ...or this PR: https://github.com/backdrop-contrib/coder_upgrade/pull/82 ...or this patch alternatively?: https://patch-diff.githubusercontent.com/raw/backdrop-contrib/coder_upgrade/pull/82.patch

**Comment by bugfolder** [comment]
@rayjamesdev, the dev version of this module now contains the patches referenced above and has been tested on PHP 8.1. Can you try it out and see if it works for you?
