### ISSUE TITLE
PHP 8.1: TypeError: set_exception_handler(): Argument #1 ($callback) must be a valid callback or null, class PGPReader does not have a method "exception_handler" in set_exception_handler()

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/coder_upgrade#83]
When running coder upgrade with PHP 8.1, trying to convert a module, I get:

```
TypeError: set_exception_handler(): Argument #1 ($callback) must be a valid callback or null, class PGPReader does not have a method "exception_handler" in set_exception_handler() (line 107 of /Users/XXX/Sites/localhost/XXX/modules/coder_upgrade/grammar_parser/parser.inc).
```

It runs find in 7.4

**Comment by docwilmot** [comment]
We did some 8.1 work few months ago, but I dont think we released. Pretty sure that was one of the errors that should have been fixed in latest dev. @bugfolder time to release you think?

**Comment by bugfolder** [comment]
Agreed

**Comment by bugfolder** [comment]
@argiepiano, can you confirm that new release 1.x-1.0.9 (released last week) fixes the problem you experienced?

**Comment by argiepiano** [comment]
Yes, the new release doesn't throw this error.  Closing.
