### ISSUE TITLE
Config settings incorrectly added to system.performance

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/coder_upgrade#84]
There are a number of config settings that are incorrectly being added to `system.performance`:

 - https://github.com/backdrop-contrib/coder_upgrade/blob/f7ba873c4e9edb4fbdfe5524a40d0246519c6346/includes/variables.inc#L475-L556

Reference from a recent issue in a contrib module queue:

 - https://github.com/backdrop-contrib/print/issues/26

**Comment by herbdool** [comment]
I've got a tiny PR for this. @docwilmot @bugfolder Would be good to get this in and a new release to prevent bugs from creeping in.

**Comment by laryn** [comment]
Looks good!

**Comment by herbdool** [comment]
Thanks @docwilmot. Would you consider creating a bug fix release that includes this?
